Repository LartTyler/MHWDB-API, pull requests merged in 2019-12, with the labels that each got.

#119 Merge fix/event-date-parsing into master
  src/WorldEvent/WorldEventReader.php
Labels: bug

#125 Added Fanged Beasts monster sub-species.
  src/Game/MonsterSpecies.php
Labels: enhancement

#128 Merge fix/outdated-packages into release/1.17.0
  .env.dist
  .gitignore
  Vagrantfile
  bin/console
  composer.json
  composer.lock
  config/bundles.php
  config/packages/doctrine.yaml
  config/packages/framework.yaml
  config/packages/veritas.yaml
  config/routes/dev/twig.yaml
  config/services.yaml
  config/services/commands.yaml
  config/services/responder.yaml
  config/services/security.yaml
  public/.htaccess
  public/index.php
  src/Command/EntityDeleteCommand.php
  src/Command/SyncEntityLengthCachesCommand.php
  src/Contrib/ApiErrors/InvalidParameterError.php
  src/Contrib/ApiErrors/MissingRequiredFieldsError.php
  src/Contrib/Transformers/UserTransformer.php
  src/Controller/AbstractController.php
  src/Controller/AilmentController.php
  src/Controller/ArmorController.php
  src/Controller/ArmorSetBonusController.php
  src/Controller/ArmorSetsController.php
  src/Controller/CharmsController.php
  src/Controller/DecorationsController.php
  src/Controller/EventController.php
  src/Controller/ItemsController.php
  src/Controller/LocationController.php
  src/Controller/MonsterController.php
  src/Controller/MonsterRewardsController.php
  src/Controller/MotionValuesController.php
  src/Controller/SchemaController.php
  src/Controller/SkillsController.php
  src/Controller/UserController.php
  src/Controller/WeaponsController.php
  src/Entity/User.php
  src/Entity/UserRole.php
  src/QueryDocument/Projection.php
  src/QueryDocument/ProjectionPathCache.php
  src/Response/UnknownWeaponTypeError.php
  symfony.lock
Labels: refactor

#129 Merge feature/iceborne-event-support into release/1.17.0
  src/Command/WorldEventSyncCommand.php
  src/Entity/WorldEvent.php
  src/Game/Expansion.php
  src/Game/WorldEventType.php
  src/Migrations/Version20191216214009.php
  src/WorldEvent/WorldEventReader.php
Labels: enhancement
